# General parameters
dataset: url
objective: binary # Don't change

# Optuna parameters - https://optuna.org/
n_trials: 2
direction: maximize

# Cross validation parameters
num_splits: 3
shuffle: True
seed: 221 # Don't change

# Preprocessing parameters
scale: True
target_encode: False
one_hot_encode: False


# About the data
num_classes: 1  # for classification
num_features: 756