# General parameters
dataset: url
objective: binary # Don't change

# Optuna parameters - https://optuna.org/
direction: maximize

# About the data
num_classes: 1  # for classification
num_features: 63